services:
    app:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        container_name: app-Rifa
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        networks:
            - Rifa-Net

    server:
        image: nginx:alpine
        container_name: server-Rifa
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - Rifa-Net

    db:
        image: mysql:8.0
        container_name: db-Rifa
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: rifa
            MYSQL_ROOT_PASSWORD: admin@
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin@
        volumes:
            - ./dbdata/:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - Rifa-Net

networks:
    Rifa-Net:
        driver: bridge
